# Generated by Django 5.1.3 on 2024-12-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dwello", "0002_remove_userprofile_preferred_city_userprofile_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
    ]
